### ISSUE TITLE
Various bugs/suggestions

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/ermineR#5]
Good news is it was not hard to get working. I had to set JAVA_HOME with Sys.setenv, otherwise no show-stoppers - just regular bugs.

Some of these discussed previously.

1. Downloads GO file every time you run it?
2. Using a data frame for scores didn't work for me. The "scoreColumn" setting is also ambiguous between the two situations. Ideally we would only support data frames, and have a better way to index the scores (e.g., by column name, or just require feeding in a single column as a df with row names or list)
3. If possible make logging output less verbose
4. Top of help says logTrans=FALSE  but help body says the default is TRUE. Is in fact FALSE by default.
5. Some of the options are pretty obscure and would not be used in normal use. For example the correlation option can be hidden (or would be a separate method)
6. Having simplified options like "ORA", "PreRe", "ROC" would be good rather than requiring test="GSR" and stats="precisionRecall".
7. Allow key diagnostics to be captured in the output object (as attributes I guess) - for example, the MF bias (correlation).

If any of these need changes on the ermineJ side, let me know. Also not all of these are important (depends on effort required) just nice to have.

**Comment by oganm** [comment]
**1** is correct provided the geneSetDescription = "Latest_GO". User can set it to a local file and use that instead. Can have a function to do a 1 time download but it'll be merely `download.file(goLink)` Then user will have to provide a filepath. Currently they can do that by... `download.file(goLink)`. 

An alternative is to download on installation or on package load, maybe with a function to update at will, but this will make it hard to track which version you are using and will cause issues if the R package is installed to a place the user doesn't have write access.

**2** Can I have the data and code you used in your attempts? `scoreColumn` can be changed to accept a number or a column name. 

**3, 4** Done. I can silence the download message as well.

**5, 6** I am considering making wrapper functions instead of directing people to use this monolithic one that exposes everything. That way obscure options with sensible defaults can be pushed to the back without consequence.

**7** is it this part of the output? Should we return it all?
```
multifunctionalityCorrelation=-0.0113
multifunctionalityEnrichment=0.4784
multifunctionalityEnrichmentPvalue=1.000
numAboveThreshold=9994
```

**Comment by ppavlidis** [comment]
1: Many bioconductor annotation packages have a "cache" option which is true by default.
2. Making `scoreColumn` by name would be good. Test case en route.
5, 6: Yes, exactly.
7: I'll have to check but the main one I wanted among those was multifunctionalityCorrelation.

**Comment by oganm** [comment]
**2** is done.
**7** is done

That leaves the wrapper functions and deciding what to do with the go annotation file.

**Comment by oganm** [comment]
4 wrapper functions are out for the 4 tests.
